### ISSUE TITLE
Latest cleanup breaks Supertext bulk process

### ISSUE THREAD

**Issue by bartTC** [divio/djangocms-translations#40]
The i18n cleanup in 32ef312a6cccb26d2f1b745f186d508fe6055c77 breaks the 'translate in bulk' process. 

```
Internal Server Error: /en-gb/admin/djangocms_translations/translationrequest/translate-in-bulk-step-3/
Traceback (most recent call last):
  File "/app/src/djangocms_translations/admin.py", line 364, in translate_in_bulk_step_3
    form.save()
  File "/app/src/djangocms_translations/forms.py", line 194, in save
    additional_info=_('Order without quote'),		<<<<<<<<<<<<<<<<<<<<<
  File "/app/src/djangocms_translations/models.py", line 111, in set_provider_options
    self.save(update_fields=('provider_options',))
TypeError: Object of type '__proxy__' is not JSON serializable
```

**Comment by FinalAngel** [comment]
Thank you for the report @bartTC, we'd welcome a PR :) 💯

**Comment by FinalAngel** [comment]
@bartTC has there been any update from your end? Is this still valid?

**Comment by bartTC** [comment]
This is still valid but I copied the entire codebase to the project and fixed it there. I just removed the lazy gettext in above code sample.

**Comment by FinalAngel** [comment]
@bartTC basically you removed ``additional_info=_('Order without quote')`` ?

**Comment by bartTC** [comment]
I did ```additional_info='Order without quote'```

If I understand correctly than this string is sent to Supertext so having it translated could be problematic anyway.

**Comment by FinalAngel** [comment]
Hm thats weird we use _() in other places as well. Did you try with ``additional_info='Order without quote'`` as well if that solves the issue?

**Comment by bartTC** [comment]
The other places are fine but here the object is converted into JSON and the lazy ugettext is not serializable. 

```TypeError: Object of type '__proxy__' is not JSON serializable```

> Did you try with additional_info='Order without quote' as well if that solves the issue?

This _is_ what I'm doing.
